#!/bin/bash

sudo rm -rf dist releases any2ascii pkg/dist/arch pkg/dist/fedora pkg/dist/rpi
[ -f Makefile ] && make distclean
rm -f aclocal.m4 compile config.h.in configure \
      depcomp install-sh Makefile.in missing src/Makefile.in
rm -rf autom4te.cache src/.deps 
